homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: CodersLabWorkshopBundle:Static:homepage.html.twig

project_planner:
    resource: "@ProjectPlannerBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

