<?php

namespace ProjectPlannerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BugRepository extends EntityRepository
{
}
