<?php

namespace ProjectPlannerBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findByUser(User $user){
        $projectsForUser = [];
        $projects = $this->findAll();

        foreach($projects as $project){
            if($project->isUserAssigned($user)) {
                $projectsForUser[] = $project;
            }
        }
        return $projectsForUser;
    }
}
